# -*- coding: utf-8 -*-
"""10_Data_Visualization_III_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QleSJ4NfJWgEX-Wq-QsutOvagH_dfQza

https://www.kaggle.com/datasets/nandaprasetia/iris-dataset-various-format-types
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/csv_data_iris.csv")
df.head()

df.columns

df.info()

"""**List down the features and their types (e.g., numeric, nominal) available in the dataset.**"""

df.dtypes

"""**Create a histogram for each feature in the dataset to illustrate the feature distributions.**"""

df.hist(figsize=(10,8))
plt.show()

"""**Create a boxplot for each feature in the dataset.**"""

sns.boxplot(data=df.iloc[:,0:4])
plt.title("Boxplots of All Numeric Features")
plt.show()
