# -*- coding: utf-8 -*-
"""5_Data_Analytics_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CuREebzLLx_owCyjScnWjyi3PCPRbs6P

Dataset: https://www.kaggle.com/datasets/rakeshrau/social-network-ads
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

df = pd.read_csv("/content/Social_Network_Ads.csv")
df.head()

df.info()

#Select Features and Target
X = df[['Age', 'EstimatedSalary']]
y = df['Purchased']

#Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

#Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Train Logistic Regression Model
model = LogisticRegression()
model.fit(X_train, y_train)

#Predict Test Results
y_pred = model.predict(X_test)
print(y_pred)

#Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

#Extract TP, FP, TN, FN
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]
print("TP =", TP)
print("FP =", FP)
print("TN =", TN)
print("FN =", FN)

#Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
print("Accuracy =", accuracy)

#Error Rate
error_rate = (FP + FN) / (TP + TN + FP + FN)
print("Error Rate =", error_rate)

#Precision
precision = TP / (TP + FP)
print("Precision =", precision)

#Recall
recall = TP / (TP + FN)
print("Recall =", recall)